# Generated by Django 3.0.11 on 2020-12-17 07:23

import apksign.contenttyperestrictedfilefield
import apksign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('file', apksign.contenttyperestrictedfilefield.ContentTypeRestrictedFileField(upload_to=apksign.models.PathAndRename('upload'))),
                ('signed', models.FileField(upload_to='package')),
                ('status', models.CharField(blank=True, max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('up_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('from_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
